Repository woowa-techcamp-2020/hkb-6, pull requests merged in 2020-07, with the labels that each got.

#13 Feature/listpage markup
  client/public/index.html
  client/public/index_bundle.js
  client/src/hello.js
  client/src/images/brocolli.png
  client/src/index.html
  client/src/index.js
  client/src/scss/_filter.scss
  client/src/scss/_form.scss
  client/src/scss/_variable.scss
  client/src/scss/main.scss
  client/src/scss/reset.scss
  client/src/style.css
  client/src/world.js
  client/webpack.dev.js
Labels: Frontend, design

#14 내역 페이지 마크업 컴포넌트 분리
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/component/Filter.js
  client/src/component/Filter.scss
  client/src/component/Form.js
  client/src/component/Form.scss
  client/src/component/Header.js
  client/src/component/Header.scss
  client/src/component/Ledger.js
  client/src/component/Ledger.scss
  client/src/component/LedgerItem.js
  client/src/component/LedgerItem.scss
  client/src/component/Navbar.js
  client/src/component/Navbar.scss
  client/src/images/cat.jpg
  client/src/index.html
  client/src/index.js
  client/src/scss/_filter.scss
  client/src/scss/main.scss
  client/store.js
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
Labels: Frontend

#15 서버 스켈레톤 코드 구현
  .gitignore
  build.sh
  client/webpack.common.js
  server/Dockerfile
  server/app.js
  server/bin/www
  server/config/utf8mb4.cnf
  server/controller/payment-controller.js
  server/db.js
  server/docker-compose.yml
  server/http/paymentApi.http
  server/model/payment.js
  server/package-lock.json
  server/package.json
  server/public/stylesheets/style.css
  server/route/api-router.js
  server/route/payment-router.js
  server/route/statistics-router.js
  server/route/transaction-router.js
  server/routes/index.js
  server/routes/users.js
  server/sql_scripts/createTable.sql
  server/views/error.jade
  server/views/index.jade
  server/views/layout.jade
Labels: Backend

#16 결제수단 관리 버튼 클리시 모달창 팝업하도록 구현
  client/src/App.js
  client/src/component/Form.js
  client/src/component/Header.js
  client/src/component/Ledger.js
  client/src/component/Modal.js
  client/src/component/Modal.scss
  client/src/component/Navbar.scss
  client/src/scss/_variable.scss
  client/src/scss/main.scss
  client/src/store.js
  client/src/util/util.js
  client/store.js
Labels: Frontend, feature

#19 pm2 패키지 추가
  server/package.json
Labels: Backend, DevOps

#20 홈페이지, 내역페이지, 달력페이지, 통계페이지 라우터 추가
  client/src/App.js
  client/src/component/Navbar.js
  client/src/pages/calendarPage.js
  client/src/pages/homePage.js
  client/src/pages/listPage.js
  client/src/pages/statisticsPage.js
  client/src/router.js
  client/src/util/util.js
Labels: Frontend, feature

#21 Form 태그 가계부 항목 추가 함수 구현
  client/src/App.js
  client/src/component/Form.js
  client/src/component/Form.scss
  client/src/component/Ledger.js
  client/src/component/LedgerItem.js
  client/src/router.js
  client/src/store.js
  client/src/util/util.js
Labels: feature

#22 Transaction GET, POST API 구현
  server/app.js
  server/controller/payment-controller.js
  server/controller/transaction-controller.js
  server/http/transactionApi.http
  server/model/payment.js
  server/model/transaction.js
  server/route/payment-router.js
  server/route/transaction-router.js
Labels: Backend, feature

#23 Form submit 관련 함수 구현
  client/src/component/Form.js
  client/src/component/Form.scss
  client/src/scss/main.scss
  client/src/store.js
  server/db.js
Labels: Frontend, bug, design, feature

#25 Ledger 컴포넌트 기능 구현
  client/src/Data.js
  client/src/component/Filter.js
  client/src/component/Filter.scss
  client/src/component/Header.js
  client/src/component/Ledger.js
  client/src/component/LedgerItem.js
  client/src/component/LedgerItem.scss
  client/src/component/Modal.js
  client/src/scss/_variable.scss
  client/src/scss/main.scss
  client/src/service/paymentService.js
  client/src/store.js
  server/model/payment.js
Labels: Frontend
