Repository woowa-techcamp-2020/hkb-6, pull requests merged in 2020-08, with the labels that each got.

#40 Client 개발 환경변수와 프로덕션 환경변수 분리
  client/.env.dev
  client/.env.prod
  client/.gitignore
  client/src/.sample.env.dev
  client/src/.sample.env.prod
  client/src/service/paymentService.js
Labels: Frontend, enhancement

#42 금액 입력 제대로 안되는 버그 수정
  client/.env.dev
  client/src/component/Form.js
  client/src/component/Form.scss
  client/src/store.js
  client/src/util/validation.js
Labels: Frontend, bug

#46 SPA 라우터 내역페이지 버그수정
  build_dev.sh
  client/.sample.env.dev
  client/.sample.env.prod
  client/package.json
  client/src/App.js
  client/src/component/Form.js
  client/src/component/Ledger.js
  client/src/component/LedgerItem.js
Labels: bug, hotfix

#47 폼 태그 submit 관련 유효성 검사 기능 구현
  client/.env.dev
  client/src/App.js
  client/src/component/Form.js
  client/src/component/Form.scss
  client/src/component/LedgerItem.js
  client/src/service/paymentService.js
  client/src/store.js
  client/src/util/validation.js
  client/webpack.common.js
Labels: Frontend, feature

#49 Filter 컴포넌트 기능 구현
  client/src/Data.js
  client/src/component/Filter.js
  client/src/component/Ledger.js
  client/src/component/LedgerItem.js
  client/src/component/LedgerItem.scss
  client/src/scss/main.scss
  client/src/util/constant.js
  client/src/util/util.js
Labels: Frontend, feature

#53 [Form feature] 수입/지출에 따라 다른 카테고리 항목 보이도록 구현
  client/src/component/CategoryList.js
  client/src/component/Form.js
  client/src/component/LedgerItem.js
  client/src/component/Navbar.scss
  client/src/router.js
  client/src/util/util.js
  server/route/api-router.js
Labels: Frontend, enhancement, feature

#58 [기능 추가] /FORM 결제수단 #57 get api와 연결
  client/src/App.js
  client/src/component/Form.js
  client/src/component/Header.js
Labels: Frontend, feature

#61 [기능추가]/Calendar <Calendar> 및 <CalendarDay>컴포넌트 기능 구현
  client/src/App.js
  client/src/component/Calendar.js
  client/src/component/Calendar.scss
  client/src/component/CalendarDay.js
  client/src/component/CalendarDay.scss
  client/src/component/CategoryList.js
  client/src/component/Filter.js
  client/src/component/Form.js
  client/src/component/Ledger.js
  client/src/component/LedgerItem.js
  client/src/component/Navbar.js
  client/src/component/Navbar.scss
  client/src/pages/calendarPage.js
  client/src/router.js
  client/src/store.js
  client/src/util/constant.js
  client/src/util/sumCalculator.js
Labels: Frontend, feature

#60 Feature/modal payment 모달에서 결제수단 추가 기능 구현
  client/src/App.js
  client/src/component/Modal.js
  client/src/component/Modal.scss
  client/src/service/paymentService.js
  client/src/store.js
  client/src/util/fetchManager.js
  server/controller/payment-controller.js
  server/controller/transaction-controller.js
  server/http/paymentApi.http
  server/model/payment.js
  server/route/payment-router.js
  server/utils/response-message.js
Labels: Frontend, feature

#67 [버그수정] #65 unsubscribe 버그 수정
  client/src/component/Calendar.js
  client/src/component/CalendarDay.js
  client/src/component/Form.js
  client/src/component/Ledger.js
  client/src/component/LedgerItem.js
Labels: Frontend, bug, hotfix

#68 Passport Google Oauth 기능 구현
  client/src/App.js
  client/src/component/Header.js
  client/src/images/google-btn.png
  client/src/pages/calendarPage.js
  client/src/pages/homePage.js
  client/src/pages/homePage.scss
  client/src/pages/listPage.js
  client/src/pages/statisticsPage.js
  client/src/router.js
  client/src/util/fetchManager.js
  server/app.js
  server/config/passport-config.js
  server/controller/transaction-controller.js
  server/http/paymentApi.http
  server/http/transactionApi.http
  server/model/transaction.js
  server/model/user.js
  server/package-lock.json
  server/package.json
  server/route/auth-router.js
  server/utils/auth.js
  server/utils/response-message.js
Labels: Backend, feature

#69 [statistics Page]통계 페이지 bar 그래프 구현 및 statisticsMenu컴포넌트 생성
  client/src/Data.js
  client/src/component/Bargraph.js
  client/src/component/Bargraph.scss
  client/src/component/Calendar.js
  client/src/component/CalendarDay.js
  client/src/component/Filter.js
  client/src/component/LedgerItem.js
  client/src/component/StatisticsMenu.js
  client/src/component/StatisticsMenu.scss
  client/src/pages/statisticsPage.js
  client/src/router.js
  client/src/scss/main.scss
  client/src/store.js
  server/model/payment.js
Labels: Frontend, design, feature

#71 Piechart 컴포넌트 구현
  client/src/Data.js
  client/src/component/PieChart.js
  client/src/component/PieChart.scss
  client/src/component/StatisticsMenu.js
  client/src/pages/statisticsPage.js
  client/src/util/constant.js
  client/src/util/util.js
  server/sql_scripts/createTable.sql
Labels: Frontend, feature

#76 [기능개선] 로그인된 유저의 정보를 가져오는 기능 구현
  server/controller/payment-controller.js
  server/controller/transaction-controller.js
  server/model/payment.js
  server/model/transaction.js
  server/route/payment-router.js
  server/utils/contant.js
Labels: Backend, enhancement

#77 [기능개선] navbar에서 월간이동 시 ledger가 해당 달에 데이터를 보여주도록 로직 수정
  client/src/component/Calendar.js
  client/src/component/CalendarDay.js
  client/src/component/Form.js
  client/src/component/Ledger.js
  client/src/component/LedgerItem.js
  client/src/pages/listPage.js
  client/src/router.js
  client/src/store.js
  client/src/util/sumCalculator.js
  client/src/util/util.js
  server/model/transaction.js
Labels: Frontend, enhancement

#80 [버그수정] getNextpageURI 함수가 import 되지 않은 버그 수정
  client/src/component/Calendar.js
  client/src/component/Form.js
  client/src/component/LedgerItem.js
Labels: bug, hotfix

#83 [기능추가] ledger Item 컴포넌트 수정 기능 구현
  client/actions
  client/src/component/Calendar.js
  client/src/component/Form.js
  client/src/component/Ledger.js
  client/src/component/LedgerItem.js
  client/src/component/LedgerItem.scss
  client/src/pages/calendarPage.js
  client/src/service/transactionService.js
  client/src/store.js
  client/src/util/util.js
  server/controller/transaction-controller.js
  server/model/transaction.js
Labels: Frontend, feature

#81 [기능추가] line graph #70 일별 지출 데이터 그래프와 연동
  client/src/component/Bargraph.scss
  client/src/component/LineGraph.js
  client/src/component/LineGraph.scss
  client/src/store.js
  client/src/util/constant.js
Labels: Frontend, feature

#84 [기능추가] Form 컴포넌트 내용지우기 기능 구현 및 transaction 삭제 api 연동
  client/src/component/Calendar.js
  client/src/component/Form.js
  client/src/component/Form.scss
  client/src/service/transactionService.js
  client/src/store.js
  client/src/util/util.js
Labels: Frontend, feature

#85 [버그수정] #82 transaction model select 쿼리 수정
  server/model/transaction.js
  server/sql_scripts/createTable.sql
Labels: bug, hotfix

#86 [Feature/nav bar] 선택한 탭에 따라 탭 style 변경
  client/src/component/Bargraph.js
  client/src/component/Calendar.js
  client/src/component/CalendarDay.js
  client/src/component/LineGraph.js
  client/src/component/LineGraph.scss
  client/src/component/Modal.js
  client/src/component/Navbar.js
  client/src/component/Navbar.scss
  client/src/component/PieChart.js
  client/src/component/StatisticsMenu.js
  client/src/pages/statisticsPage.js
  client/src/store.js
  client/src/util/constant.js
Labels: Frontend, feature

#88 GET statistics api 구현
  client/src/component/Bargraph.js
  client/src/component/PieChart.js
  client/src/pages/statisticsPage.js
  client/src/service/statisticsService.js
  client/src/store.js
  server/controller/statistics-controller.js
  server/http/statisticsApi.http
  server/model/transaction.js
  server/route/statistics-router.js
Labels: Backend, feature

#91 [기능개선] piechart 및 statmenu 컴포넌트 style개선
  client/src/component/PieChart.js
  client/src/component/PieChart.scss
  client/src/component/StatisticsMenu.js
  client/src/component/StatisticsMenu.scss
  client/src/util/constant.js
Labels: Frontend, enhancement

#93 list page style 추가 및 line bar 버그 수정, edit버튼 클릭시 화면 상단 스크롤 구현
  client/src/component/Form.js
  client/src/component/Form.scss
  client/src/component/LedgerItem.js
  client/src/component/LedgerItem.scss
  client/src/component/LineGraph.js
  client/src/component/LineGraph.scss
  client/src/pages/listPage.js
Labels: Frontend, bug, enhancement, feature, hotfix

#97 [버그수정] #94 calendar, statistics 페이지에서 달력 이동시 filter의 총액이 바뀌지 않는 버그 수정
  client/src/component/Filter.js
  client/src/component/Navbar.js
Labels: Frontend, bug, hotfix

#99 [기능추가] 서버에서 pm2, morgan을 이용해 로그를 기록하는 로직 추가
  server/app.js
  server/config/logger-config.js
  server/package.json
Labels: Backend, feature

#98 [기능추가] statistics menu #89 월간 지출 합계 api와 utils함수 연동
  client/src/component/ComparisonGraph.js
  client/src/component/ComparisonGraph.scss
  client/src/component/LineGraph.js
  client/src/component/PieChart.js
  client/src/component/StatisticsMenu.js
  client/src/util/util.js
  server/http/statisticsApi.http
  server/http/transactionApi.http
Labels: Frontend, enhancement, feature

#102 [버그수정] #101 통계페이지 월간이동시 그래프가 새로 그려지지 않는 버그 수정
  client/src/component/Bargraph.js
  client/src/component/LineGraph.js
  client/src/component/PieChart.js
  client/src/component/PieChart.scss
  client/src/pages/statisticsPage.js
  client/src/store.js
Labels: Frontend, bug, enhancement, hotfix

#105 [문서] README installation guide 추가
  README.md
  client/README.md
Labels: documentation

#106 [버그수정] #100 Form 컴포넌트 select 유효성 검사 버그 수정
  client/src/component/Form.js
Labels: Frontend, bug, hotfix

#107 [기능개선] 내역이 없는 달의 통계페이지 UI 추가
  client/src/component/Bargraph.js
  client/src/component/LineGraph.js
  client/src/component/PieChart.js
  client/src/component/PieChart.scss
  client/src/component/StatisticsMenu.js
  client/src/images/google-btn.png
  client/src/images/google-signin-btn.svg
  client/src/images/tung.svg
  client/src/pages/homePage.js
  client/src/pages/homePage.scss
  client/src/pages/statisticsPage.js
Labels: Frontend, enhancement

#109 [버그수정] #74 결제 수단을 삭제 했을때 transaction 테이블의 레코드가 연쇄적으로 삭제되는 버그 수정
  server/model/payment.js
  server/utils/contant.js
Labels: Backend, bug, hotfix

#108 Feature/stacked bar
  client/src/component/Bargraph.js
  client/src/component/LineGraph.js
  client/src/component/LineGraph.scss
  client/src/component/Navbar.js
  client/src/component/Navbar.scss
  client/src/component/StackedBar.js
  client/src/component/StackedBar.scss
  client/src/pages/homePage.js
  client/src/pages/homePage.scss
  client/src/pages/statisticsPage.js
  client/src/store.js
Labels: Frontend, feature
